# Generated by Django 2.2.17 on 2020-11-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nname', models.CharField(max_length=50)),
                ('site', models.URLField()),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='salessite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('site', models.URLField()),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('mapp', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=None, default='new', upload_to='shop_poster')),
                ('price', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.company')),
                ('salessite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.salessite')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='salessite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.salessite'),
        ),
    ]
