# Generated by Django 2.2.17 on 2020-11-09 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201108_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='salessite',
        ),
        migrations.AddField(
            model_name='salessite',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.company'),
        ),
    ]
